[tox]
minversion = 4.0
envlist =
    py312-django{60,61,main}
isolated_build = true

[testenv]
description = pytest on Python {envpython} with {envname}
package = skip
deps =
    pytest>=8
    fashion-size>=2026.10.8.1
    django60: Django>=6.0,<6.1
    django61: Django>=6.1,<6.2
    djangomain: https://github.com/django/django/archive/main.tar.gz
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest {posargs:tests}
