[tox]
minversion = 4.0
envlist =
    py312-django{42,52,60,61,main}
isolated_build = true

[testenv]
description = pytest on Python {envpython} with {envname}
package = skip
deps =
    pytest>=8
    fashion-size
    django42: Django>=4.2,<4.3
    django52: Django>=5.2,<5.3
    django60: Django>=6.0,<6.1
    django61: Django>=6.1,<6.2
    djangomain: https://github.com/django/django/archive/main.tar.gz
setenv =
    PYTHONPATH = {toxinidir}/src
commands =
    pytest {posargs:tests}
